version: '3.8'

services:
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
      - VERSION=docker
    volumes:
      - ~/plex/config:/config
      - /Volumes:/mnt/shares
    ports:
      - 32400:32400
    restart: unless-stopped
    healthcheck:
      test: curl --connect-timeout 15 --silent --show-error --fail http://localhost:32400/identity
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
  tautulli:
    image: lscr.io/linuxserver/tautulli:latest
    container_name: tautulli
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
    volumes:
      - tautilli-config:/config
    ports:
      - 8181:8181
    restart: unless-stopped
    depends_on:
      - plex
    healthcheck:
      test: curl --connect-timeout 15 --silent --show-error --fail http://localhost:8181/status
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
  transmission:
    image: lscr.io/linuxserver/transmission:latest
    container_name: transmission
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
      - USER=${TRANSMISSION_USER}
      - PASS=${TRANSMISSION_PASS}
      - WHITELIST=${TRANSMISSION_WHITELIST}
      - PEERPORT=${TRANSMISSION_PEERPORT}
      - HOST_WHITELIST=${TRANSMISSION_HOST_WHITELIST}
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    volumes:
      - transmission-config:/config
      - ~/Downloads:/downloads
      - ~/Public/watch:/watch
      - /Volumes:/mnt/shares
    restart: unless-stopped
  grafana:
    image: grafana/grafana
    container_name: grafana
    environment:
      - GF_SECURITY_ADMIN_USER=${GF_SECURITY_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD}
    volumes:
      - grafana-data:/var/lib/grafana
      - grafana-conf:/etc/grafana
    ports:
      - 3000:3000
    restart: unless-stopped
    healthcheck:
      test: curl --connect-timeout 15 --silent --show-error --fail http://localhost:3000/api/health
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
  uptime-kuma:
    image: louislam/uptime-kuma:latest
    container_name: uptime-kuma
    volumes:
      - uptime-kuma:/app/data
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 3001:3001
    restart: always

volumes:
  grafana-data:
  grafana-conf:
  tautilli-config:
  transmission-config:
  uptime-kuma:
