version: '3'

name: 'nas-tools'
services:
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
      - VERSION=docker
    volumes:
      - ~/plex/config:/config
      - /Volumes:/mnt/shares
    restart: unless-stopped
  tautulli:
    image: lscr.io/linuxserver/tautulli:latest
    container_name: tautulli
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
    volumes:
      - tautilli_config:/config
    ports:
      - 8181:8181
    restart: unless-stopped
    depends_on:
      - plex
  deluge:
    image: lscr.io/linuxserver/deluge:latest
    container_name: deluge
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
      - DELUGE_LOGLEVEL=error #optional
    volumes:
      - deluge_config:/config
      - ~/Downloads:/downloads
      - /Volumes:/mnt/shares
    ports:
      - 8112:8112
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped
  grafana:
    image: grafana/grafana
    container_name: grafana
    environment:
      - GF_SECURITY_ADMIN_USER=${GF_SECURITY_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD}
    volumes:
      - grafana-data:/var/lib/grafana
      - grafana-conf:/etc/grafana
    ports:
      - 3000:3000
    restart: unless-stopped

  reverse-proxy:
    image: traefik:v2.0
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ./traefik.toml:/etc/traefik/traefik.toml
    labels:
      - "traefik.http.routers.api.rule=Host(`traefik.home.volchan.net`)"
      - "traefik.http.routers.api.service=api@internal"
      - "traefik.http.routers.api.entrypoints=http"
      - "traefik.http.routers.api.middlewares=auth"
      - "traefik.http.middlewares.auth.basicauth.users=${TRAEFIK_AUTH}"
    restart: unless-stopped

volumes:
  deluge_config:
  grafana-data:
  grafana-conf:
  tautilli_config:
