---
version: '3.8'

services:
  grafana:
    image: grafana/grafana
    container_name: grafana
    environment:
      - GF_SECURITY_ADMIN_USER=${GF_SECURITY_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD}
    volumes:
      - data:/var/lib/grafana
      - config:/etc/grafana
    ports:
      - ${GRAFANA_PORT}:3000
    restart: unless-stopped

volumes:
  data:
  config:
