---
version: '3.8'

services:
  grafana:
    image: grafana/grafana
    container_name: grafana
    environment:
      - GF_SECURITY_ADMIN_USER=${GF_SECURITY_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD}
    volumes:
      - data:/var/lib/grafana
      - config:/etc/grafana
    ports:
      - ${GRAFANA_PORT}:3000
    restart: unless-stopped

  dozzle:
    container_name: dozzle
    image: amir20/dozzle:latest
    environment:
      DOZZLE_USERNAME_FILE: /var/run/dozzle/dozzle_user.txt
      DOZZLE_PASSWORD_FILE: /var/run/dozzle/dozzle_password.txt
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /Users/volnas/dozzle-config:/var/run/dozzle
    ports:
      - ${DOZZLE_PORT}:8080

volumes:
  data:
  config:
