version: '3.8'

services:
  transmission:
    image: lscr.io/linuxserver/transmission:latest
    container_name: transmission
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
      - USER=${TRANSMISSION_USER}
      - PASS=${TRANSMISSION_PASS}
      - WHITELIST=${TRANSMISSION_WHITELIST}
      - PEERPORT=${TRANSMISSION_PEERPORT}
      - HOST_WHITELIST=${TRANSMISSION_HOST_WHITELIST}
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    volumes:
      - transmission-config:/config
      - ~/Downloads:/downloads
      - ~/Public/watch:/watch
      - /Volumes:/mnt/shares
    restart: unless-stopped
  
  uptime-kuma:
    image: louislam/uptime-kuma:latest
    container_name: uptime-kuma
    volumes:
      - uptime-kuma:/app/data
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 3001:3001
    restart: always
  heimdall:
    image: lscr.io/linuxserver/heimdall:latest
    container_name: heimdall
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
    volumes:
      - heimdall-config:/config
    ports:
      - ${HEIMDALL_HTTP_PORT}:80
      - ${HEIMDALL_HTTPS_PORT}:443
    restart: unless-stopped

volumes:
  grafana-data:
  grafana-conf:
  heimdall-config:
  transmission-config:
  uptime-kuma:
