version: '3'

services:
  db:
    image: postgres:13
    restart: always
    container_name: nextcloud-db
    environment:
      POSTGRES_PASSWORD: ${NEXTCLOUD_PG_PASSWORD}
      POSTGRES_USER: ${NEXTCLOUD_PG_USER}
      POSTGRES_DB: ${NEXTCLOUD_PG_DB}
    volumes:
      - db-data:/var/lib/postgresql/data

  redis:
    image: redis:6
    restart: always
    container_name: nextcloud-redis
    volumes:
      - redis-data:/data

  app:
    image: nextcloud:latest
    restart: always
    container_name: nextcloud
    depends_on:
      - db
      - redis
    ports:
      - ${NEXTCLOUD_PORT}:80
    environment:
      POSTGRES_HOST: db
      POSTGRES_PASSWORD: ${NEXTCLOUD_PG_PASSWORD}
      POSTGRES_USER: ${NEXTCLOUD_PG_USER}
      POSTGRES_DB: ${NEXTCLOUD_PG_DB}
      REDIS_HOST: redis
      NEXTCLOUD_TRUSTED_DOMAINS: ${NEXTCLOUD_TRUSTED_DOMAINS}
      NEXTCLOUD_ADMIN_USER: ${NEXTCLOUD_ADMIN_USER}
      NEXTCLOUD_ADMIN_PASSWORD: ${NEXTCLOUD_ADMIN_PASSWORD}
    volumes:
      - data:/var/www/html
      - config:/var/www/html/config
      - apps:/var/www/html/custom_apps
      - themes:/var/www/html/themes

volumes:
  db-data:
  redis-data:
  data:
  config:
  apps:
  themes:
